num1=int(input('enter no. 1\n'))
num2=int(input('enter no. 2\n'))
num3=int(input('enter no. 3\n'))
num4=int(input('enter no. 4\n'))
num5=int(input('enter no. 5\n'))
num6=int(input('enter no. 6\n'))
num7=int(input('enter no. 7\n'))
num8=int(input('enter no. 8\n'))
a={num1,num2,num3,num4,num5,num6,num7,num8}
print(a)